#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

ip="127.17.0.2"; 

docker run -it \
  --name myride_test_server \
  --env ROS_MASTER_URI=http://$ip:11311 \
  --env ROS_HOSTNAME=$ip \
  -p 8080:8080 \
  -p 8000:8000 \
  -p 11311:11311 \
  --rm \
  myride_test_server "$@"

# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
