#!/bin/bash

#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"


if [ -z ${1} ]; 
then 
    ip="localhost"; 
else 
    ip=$1; 
fi


docker run -it \
  --name myride_test_server \
  --volume ${PROJECT_ROOT}/ws_testserver:/ws_testserver \
  --env ROS_MASTER_URI=http://$ip:11311 \
  --env ROS_HOSTNAME=$ip \
  -p 8080:8080 \
  -p 8000:8000 \
  --rm \
  myride_test_server roslaunch myride_test_server test1.launch address:=$ip


# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
